//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "agent_rooms")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub agent_id: String,
    pub instance_id: Option<String>,
    pub room_name: String,
    pub joined_at: Option<DateTime>,
    pub left_at: Option<DateTime>,
    pub created_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::agents::Entity",
        from = "Column::AgentId",
        to = "super::agents::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Agents,
    #[sea_orm(
        belongs_to = "super::agent_instances::Entity",
        from = "Column::InstanceId",
        to = "super::agent_instances::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    AgentInstances,
}

impl Related<super::agents::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Agents.def()
    }
}

impl Related<super::agent_instances::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AgentInstances.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
