//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "agent_instances")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub agent_id: String,
    pub instance_id: String,
    pub container_id: Option<String>,
    pub process_pid: Option<i32>,
    pub status: String,
    pub last_heartbeat: Option<DateTime>,
    pub exit_code: Option<i32>,
    pub crash_reason: Option<String>,
    pub started_at: Option<DateTime>,
    pub stopped_at: Option<DateTime>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::agents::Entity",
        from = "Column::AgentId",
        to = "super::agents::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Agents,
    #[sea_orm(has_many = "super::agent_logs::Entity")]
    AgentLogs,
    #[sea_orm(has_many = "super::agent_metrics::Entity")]
    AgentMetrics,
    #[sea_orm(has_many = "super::agent_rooms::Entity")]
    AgentRooms,
}

impl Related<super::agents::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Agents.def()
    }
}

impl Related<super::agent_logs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AgentLogs.def()
    }
}

impl Related<super::agent_metrics::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AgentMetrics.def()
    }
}

impl Related<super::agent_rooms::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AgentRooms.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
