//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub mod prelude;

pub mod users;
pub mod api_keys;
pub mod rooms;
pub mod ingress;
pub mod egress;
pub mod sip;
pub mod configs;
pub mod metrics;
pub mod agents;
pub mod agent_instances;
pub mod agent_logs;
pub mod agent_metrics;
pub mod agent_rooms;

pub mod projects;
pub mod project_ai_configs;
pub mod sessions;
pub mod analytics_snapshots;
pub mod sip_trunks;
pub mod dispatch_rules;
pub mod room_templates;
pub mod layout_templates;
pub mod auto_recording_rules;
pub mod service_accounts;
pub mod storage_configs;
pub mod regions;
pub mod roles;
pub mod audit_logs;
pub mod transcripts;
pub mod webhook_events;
pub mod webhook_deliveries;
pub mod error_logs;
